services:
  - name: airflow-webserver
    type: web
    runtime: docker
    repo: https://github.com/MadhurDixit13/Reddit-Sentiment-Analysis-Data-Pipeline.git
    branch: main
    startCommand: "airflow webserver" 
    envVars:
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromService: postgres-db
      - key: REDIS_URL
        fromService: redis-db
    plan: free
    dockerCommand: ["airflow", "webserver"]

  - name: airflow-scheduler
    type: background
    runtime: docker
    repo: https://github.com/MadhurDixit13/Reddit-Sentiment-Analysis-Data-Pipeline.git
    branch: main
    startCommand: "airflow scheduler" 
    envVars:
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromService: postgres-db
    plan: free
    dockerCommand: ["airflow", "scheduler"]

  - name: airflow-worker
    type: background
    runtime: docker
    repo: https://github.com/MadhurDixit13/Reddit-Sentiment-Analysis-Data-Pipeline.git
    branch: main
    startCommand: "airflow celery worker"
    envVars:
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromService: postgres-db
    plan: free
    dockerCommand: ["airflow", "celery", "worker"]

  - name: streamlit-dashboard
    type: web
    runtime: docker
    repo: https://github.com/MadhurDixit13/Reddit-Sentiment-Analysis-Data-Pipeline.git
    branch: main
    startCommand: "streamlit run dashboard_app.py --server.port=8080 --server.address=0.0.0.0"
    envVars:
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
    plan: free
    dockerCommand: ["streamlit", "run", "dashboard_app.py", "--server.port=8080", "--server.address=0.0.0.0"]
databases:
  - name: postgres-db
    databaseName: postgres
    user: postgres
    plan: free
    ipAllowList: []

  - name: redis-db
    plan: free
    ipAllowList: []
