name: CI/CD for Airflow & Streamlit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Airflow Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/airflow:latest

      - name: Build and push Streamlit Dashboard image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./StreamlitDockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/streamlit-dashboard:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/airflow:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/streamlit-dashboard:latest
            docker-compose down
            docker-compose up -d
            docker system prune -f
      - name: Set Airflow Secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker ps --format "table {{.Names}}\t{{.Status}}"
          docker-compose exec airflow-webserver airflow variables set AWS_ACCESS_KEY "${{ secrets.AWS_ACCESS_KEY }}"
          docker-compose exec airflow-webserver airflow variables set AWS_SECRET_KEY "${{ secrets.AWS_SECRET_KEY }}"
          docker-compose exec airflow-webserver airflow variables set S3_BUCKET_NAME "${{ secrets.S3_BUCKET_NAME }}"
          docker-compose exec airflow-webserver airflow variables set REDDIT_CLIENT_ID "${{ secrets.REDDIT_CLIENT_ID }}"
          docker-compose exec airflow-webserver airflow variables set REDDIT_CLIENT_SECRET "${{ secrets.REDDIT_CLIENT_SECRET }}"
          docker-compose exec airflow-webserver airflow variables set REDDIT_USER_AGENT "${{ secrets.REDDIT_USER_AGENT }}"
